services:

  db:
    image: mongo:7
    restart: always
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - ./mongo_data:/data/db
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER?Variable not set}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD?Variable not set}
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    command: >
      redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mongo_data:
  redis_data:
